### PR TITLE
Update Steampunk_Advanced.xml

### PR DESCRIPTION
**Pull request by trohwer**
Add some missing connections (using the GUI map as reference).

### CODE REVIEW

**Comment by CharlieAtlas** [comment]
I am compiling a list of map PRs to hopefully get pulled.  
Do we know for sure that the connections are supposed to be there?

**Comment by SwampyAcres** [comment]
> I am compiling a list of map PRs to hopefully get pulled.
> Do we know for sure that the connections are supposed to be there?

I'm sorry what connections are you talking about?

**Comment by CharlieAtlas** [comment]
The commit is for some missing territory connections.  Most of the territories are either neutrals or worth 0, so I was wondering if they are supposed to be connected or not.  I assume so, but figured verification is always good.

**Comment by SwampyAcres** [comment]
Okay I understand. I inherited these connection issues when I upgraded the map from the original Steampunk. They still exist in "Steampunk Advanced". I have a draft version on my desktop where I am slowly fixing these (I have all the connection issues in Canada corrected.. but haven't started on the neutrals). I am not sure when I will be done with this.. as I have other error corrections and additions planned for my next release. Is that helpful information? Not sure why you need this info.

**Comment by CharlieAtlas** [comment]
I didn't know if those territories were supposed to be disconnected.  Maybe the creator of the map did that on purpose.  But seeing as how you seem to be the creator of this version, you can do whatever you want.

**Comment by trohwer** [comment]
Well, the involved land pieces may not be that important. But for the user it is somewhat confusing, that they exist, but you cannot move in or out of them without any visual feedback.

**Comment by SwampyAcres** [comment]
Hi Folks.. 

 I have corrected all this connection issues and am working towards releasing a new version. There should be no territories that do not work correctly anymore. Another thing I want to do is convert the standalone game manual into the game notes section. The original creator of this map made a standalone (pdf) game manual that explains many aspects of the game. The manual is very good, but it is a large file and confusing to the players (need to read a separate document to figure out tech, etc.) I am moving this to game notes section. When I complete this and some other balance issues, I will release a new version. Hopefully very soon.

**Pull request merged**
